# Generated by Django 2.2.1 on 2019-06-15 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_request',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request', models.TextField(verbose_name='要望')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Mt_Service', verbose_name='サービスタイプ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
